[tool.autopep8]
recursive = true
in-place = true
aggressive = 2
ignore = ["E501"]

[tool.pylint.main]
recursive = true

[tool.pylint."messages control"]
disable = [
    "R0801", # duplicate lines
    "W0511", # TODO, FIXME
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "invalid-name",
]