from typing import List

TIMEOUT_IN_SECONDS = 30 * 60

PROXMOX_VM_ID_RANGE = [100, 99999]
PROXMOX_VM_TAG_DELIMITER = ";"

# https://github.com/etcd-io/etcd/issues/13670
CONTAINERD_CONFIG = """# generated by kp
version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".containerd]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
"""

KUBERNETES_ADMIN_CONF_PATH = "/etc/kubernetes/admin.conf"
KUBERNETES_CERT_PATHS = [
    "/etc/kubernetes/pki/ca.crt",
    "/etc/kubernetes/pki/ca.key",
    "/etc/kubernetes/pki/sa.key",
    "/etc/kubernetes/pki/sa.pub",
    "/etc/kubernetes/pki/front-proxy-ca.crt",
    "/etc/kubernetes/pki/front-proxy-ca.key",
    "/etc/kubernetes/pki/etcd/ca.crt",
    "/etc/kubernetes/pki/etcd/ca.key",
]
KUBERNETES_STATIC_POD_DIR = "/etc/kubernetes/manifests/"
KUBEVIP_MANIFEST_FILENAME = "kube-vip.yaml"
HAPROXY_CFG_PATH = "/etc/haproxy/haproxy.cfg"


class Cfg:
    def __init__(
            self,
            proxmox_node: str,
            proxmox_host: str,
            proxmox_port=8006,
            proxmox_verify_ssl=False,
            proxmox_user: str = None,
            proxmox_password: str = None,
            proxmox_token_name: str = None,
            proxmox_token_value: str = None,
            vm_id_range: List[int] = PROXMOX_VM_ID_RANGE,
            vm_preserved_ids: List[int] = [],
            vm_preserved_ips: List[str] = [],
            vm_ssh_keys: str = "",
            vm_name_prefix="i-",
            **kwargs) -> None:
        self.proxmox_node = proxmox_node
        self.proxmox_host = proxmox_host
        self.proxmox_port = proxmox_port
        self.proxmox_verify_ssl = proxmox_verify_ssl
        self.proxmox_user = proxmox_user
        self.proxmox_password = proxmox_password
        self.proxmox_token_name = proxmox_token_name
        self.proxmox_token_value = proxmox_token_value
        self.vm_id_range = vm_id_range
        self.vm_preserved_ids = vm_preserved_ids
        self.vm_preserved_ips = vm_preserved_ips
        self.vm_ssh_keys = vm_ssh_keys
        self.vm_name_prefix = vm_name_prefix
        self.kwargs = kwargs


class Tag:
    lb = "k8s-lb"
    ctlpl = "k8s-ctlpl"
    wk = "k8s-wk"
    kp = "kp"
