TIMEOUT_IN_SECONDS = 30 * 60  # 30 min

PROXMOX_VM_ID_RANGE = [100, 99999]
PROXMOX_VM_TAG_DELIMITER = ";"

KUBERNETES_ADMIN_CONF_LOCATION = "/etc/kubernetes/admin.conf"
KUBERNETES_CERT_PATHS = [
    "/etc/kubernetes/pki/ca.crt",
    "/etc/kubernetes/pki/ca.key",
    "/etc/kubernetes/pki/sa.key",
    "/etc/kubernetes/pki/sa.pub",
    "/etc/kubernetes/pki/front-proxy-ca.crt",
    "/etc/kubernetes/pki/front-proxy-ca.key",
    "/etc/kubernetes/pki/etcd/ca.crt",
    "/etc/kubernetes/pki/etcd/ca.key",
]

HAPROXY_CONFIG_LOCATION = "/etc/haproxy/haproxy.cfg"
HAPROXY_CONFIG_TEMPLATE = """# generated by kp
defaults
    log     global
    mode    http
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend stats
    mode http
    bind *:8404
    stats enable
    stats uri /stats
    stats refresh 10s
    stats admin if LOCALHOST

frontend api-server
    mode tcp
    bind 0.0.0.0:6443
    default_backend control-plane

backend control-plane
    mode tcp
    option httpchk GET /healthz
    http-check expect status 200
    option ssl-hello-chk
    balance roundrobin
{control_plane_backends}
"""

UPGRADE_WORKER_SCRIPT = """# Add the repository for K8S
kubernetes_version="{kubernetes_version_minor}"
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/v$kubernetes_version/deb/Release.key | gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v$kubernetes_version/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

# Install kubernetes dependencies
apt-get update
apt install -y kubeadm='{kubernetes_version_patch}-*'

sudo kubeadm upgrade node
"""


class Tag:
    lb = "k8s-lb"
    ctlpl = "k8s-ctlpl"
    wk = "k8s-wk"
    kp = "kp"
