# Powered by Gemini

name: build kp

on:
  push:
    tags:
      - v*

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/kp
  GIT_TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
      - name: set-env
        id: get_tags
        run: |
          FULL_COMMIT_HASH="${{ github.sha }}"
          echo "FULL_COMMIT_HASH=${FULL_COMMIT_HASH}" >> $GITHUB_ENV
          SHORT_COMMIT_HASH="${FULL_COMMIT_HASH:0:7}"
          echo "SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}" >> $GITHUB_ENV
      - id: buildx
        name: buildx
        uses: docker/setup-buildx-action@v3
      - id: login
        name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.get_tags.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV
      - id: noti
        name: noti
        if: ${{ always() }}
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name="$github_workflow"
          run_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          MESSAGE="${status:-bad} $workflow_name \`${{ env.DOCKER_IMAGE }}:${{ env.GIT_TAG }}\` $run_url"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
